services:
  bloglist-frontend:
    image: bloglist-frontend
    container_name: bloglist-frontend
    build:
      context: ./bloglist-frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
  bloglist-backend:
    image: bloglist-backend
    container_name: bloglist-backend
    build:
      context: ./bloglist-backend
      dockerfile: ./Dockerfile
    ports:
      - 3003:3003 
    volumes:
      - ./bloglist-backend:/usr/src/app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - bloglist-frontend 

